### ISSUE TITLE
IncludeHeaderFooter(false) dont working

### ISSUE THREAD

**Issue by gregorybarros** [adobe/PDFServices.NET.SDK.Samples#12]
I am trying to generate a PDF with HTML dynamic and the option .IncludeHeaderFooter(false) not working, the header and footer remains

` 

        public TemplateRenderer()
        {
            pageLayout = new PageLayout();
            pageLayout.SetPageSize(8, 11.5);
        }

        public string Render(object data, string template)
        {
            var executionContext = ExecutionContext.Create(credentials);
            var operation = CreatePDFOperation.CreateNew();

            var templatePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
                "Templates", 
                template, 
                "build.zip");
                
            var source = FileRef.CreateFromLocalFile(templatePath);
            operation.SetInput(source);

            var jsonData = new JObject
            {
                { "title", "Create, Convert PDFs and More!" },
                { "sub_title", "Easily integrate PDF actions within your document workflows." },
                { "data", JsonSerializer.Serialize(data) }
            };

            var options = CreatePDFOptions.HtmlOptionsBuilder()
                .IncludeHeaderFooter(false)
                .WithPageLayout(pageLayout)
                .WithDataToMerge(jsonData)
                .Build();
            operation.SetOptions(options);

            var result = operation.Execute(executionContext);

            var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Reports", $"{template}-{Guid.NewGuid()}.pdf");
            result.SaveAs(path);
            return path;
        }
    } `

**Comment by gregorybarros** [comment]
![image](https://user-images.githubusercontent.com/60372532/120829914-55008200-c534-11eb-9d95-5dd95015fb4b.png)

**Comment by namangupta21** [comment]
@gregorybarros - Thanks a lot for using the product and reporting the issue. Your feedback is very valuable to us.

We are glad to share the update on the issue. We have rolled out a fix for this in the latest version of our SDK. Please find the new bundle at https://www.nuget.org/packages/Adobe.PDFServicesSDK/2.0.0.

Please update your application with the latest SDK version 2.0.0 and re-try the workflow. The flag should work as expected now. Please let us know if you see any other issues.

Hope this helps.

**Comment by namangupta2100** [comment]
@gregorybarros - Did the fix work for you?

**Comment by anubhav-mhjn** [comment]
Closing this issue since it has been idle from long. Please feel free to re-open it in case of further queries.
