### ISSUE TITLE
Guidance and XFA Support?

### ISSUE THREAD

**Issue by krispenner** [adobe/PDFServices.NET.SDK.Samples#16]
I’m looking for some guidance here. We are provided PDF’s from our clients, we were looking to use XFA on them to add data fields and then some C# SDK to populate the data fields. I have come across your SDK in my research and have some questions

1. Do you offer XFA support? I don’t see it listed as an option. 
1. I find it very interesting you would support MS Word templates as opposed to your own XFA format, what’s the reason for that?
1. Assuming you don’t support XFA, would you suggest we convert our client’s PDFs to Word templates, populate the data and then output as PDF? I’m worried this could look terrible and lose formatting of theirs with all the conversions. 
1. Do you have any highly recommended partner services that support XFA data population via C#?
1. Would you suggest something else for us?

Cheers,
Kris

**Comment by hitesh-kumar-mahour** [comment]
Hi @krispenner, issues raised here should address problems in the samples for this repo. Closing this ticket.

Adobe community forum will be the appropriate place to raise such queries: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK.
